/*
 *                   江城子 . 程序员之歌
 *
 *               十年生死两茫茫，写程序，到天亮。
 *                   千行代码，Bug何处藏。
 *               纵使上线又怎样，朝令改，夕断肠。
 *
 *               领导每天新想法，天天改，日日忙。
 *                   相顾无言，惟有泪千行。
 *               每晚灯火阑珊处，夜难寐，加班狂。
 *
 *
 * @Author:
 * @Date: 2023-12-29 15:26:24
 * @LastEditors: Please set LastEditors
 * @LastEditTime: 2024-06-06 10:34:57
 * @FilePath: \pc\src\store\mutation_types.js
 * @Description: 头部注释
 */

export const SET_CHAT_CONTACTS_LIST = "SET_CHAT_CONTACTS_LIST";
export const SET_CHAT_USER = "SET_CHAT_USER";
export const ADD_CHAT_CONTACT = "ADD_CHAT_CONTACT";
export const ADD_CHAT_MANAGER = "ADD_CHAT_MANAGER";
export const SET_CHAT_MANAGER = "SET_CHAT_MANAGER";
export const DEL_CHAT_CONTACT = "DEL_CHAT_CONTACT";
export const UPDATE_CHAT_CONTACT = "UPDATE_CHAT_CONTACT";
export const SET_CHAT_LOADING_MORE_MESSAGE = "SET_CHAT_LOADING_MORE_MESSAGE";
export const IS_CONTACTS_JOIN_SUCCESS = "IS_CONTACTS_JOIN_SUCCESS";
export const UPDATE_MESSAGE_ULIST = "UPDATE_MESSAGE_ULIST";
export const SET_CHAT_SHOW_PRIVATE_WIN = "SET_CHAT_SHOW_PRIVATE_WIN";
export const SET_CHAT_CURRENT_CONTACT = "SET_CHAT_CURRENT_CONTACT";
export const UPATE_CHAT_CONTACT_MESSAGE = "UPATE_CHAT_CONTACT_MESSAGE";
export const UPDATE_CHAT_MANAGER_MESSAGE = "UPDATE_CHAT_MANAGER_MESSAGE";
export const SET_RY_CONNECT_SUCCESS = "SET_RY_CONNECT_SUCCESS";
export const UPDATE_UNREAD_COUNT = "UPDATE_UNREAD_COUNT";
export const SET_CHAT_CURRENT_ROOM = "SET_CHAT_CURRENT_ROOM";
export const SET_CHAT_CONTACT_ROOMINFO = "SET_CHAT_CONTACT_ROOMINFO";
export const SET_CHAT_ISLOADING_USERLIST = "SET_CHAT_ISLOADING_USERLIST";
export const SET_SHOW_SINGLE_PRIVATE_MSG_NOTICE =
  "SET_SHOW_SINGLE_PRIVATE_MSG_NOTICE";
export const SET_OPEN_PRIVATE_MSG_NOTICE_SWITCH =
  "SET_OPEN_PRIVATE_MSG_NOTICE_SWITCH";
export const SET_CODE_503_DATA = "SET_CODE_503_DATA";
export const REMOVE_CHAT_PRIVATE_MESSAGE = "REMOVE_CHAT_PRIVATE_MESSAGE";
export const SET_CHAT_PUSH_MEMBER_MSG = "SET_CHAT_PUSH_MEMBER_MSG"; // 后台推送会员消息

export const SET_LOTTERY_SELECT_LIST = "SET_LOTTERY_SELECT_LIST";
export const SET_TREND_HISTORY_LIST = "SET_TREND_HISTORY_LIST";
export const ADD_TREND_HISTORY_ITEM_BEFORE = "ADD_TREND_HISTORY_ITEM_BEFORE";
export const UPDATE_TREND_HISTORY_ITEM = "UPDATE_TREND_HISTORY_ITEM";
export const SET_LOTTERY_INFO = "SET_LOTTERY_INFO";
export const SET_DEFAULT_LOTTERY_SELECT = "SET_DEFAULT_LOTTERY_SELECT";
export const SET_LOTTERY_BUY_LOTTERY_TYPE = "SET_LOTTERY_BUY_LOTTERY_TYPE";
export const SET_LOTTERY_BUY_LOTTERY_SHOW_PLAY_RULE =
  "SET_LOTTERY_BUY_LOTTERY_SHOW_PLAY_RULE";

// rongyun.js 融云相关
export const SAVE_RONGYUN_INFO = "SAVE_RONGYUN_INFO";
export const SAVE_RONGYUN_TOKEN_INFO = "SAVE_RONGYUN_TOKEN_INFO";
export const SAVE_RONGYUN_CHATROOM_JOIN_STATUS =
  "SAVE_RONGYUN_CHATROOM_JOIN_STATUS";
export const SAVE_RONGYUN_CONNECT_STATUS = "SAVE_RONGYUN_CONNECT_STATUS";
export const ADD_RONGYUN_MESSAGE = "ADD_RONGYUN_MESSAGE";
export const SAVE_RONGYUN_CONVERSATION_LIST = "SAVE_RONGYUN_CONVERSATION_LIST";

// sysDict.js 系统配置相关
export const SAVE_SYSTEM_CONFIG = "SAVE_SYSTEM_CONFIG";
export const SAVE_SYSTEM_API_COIN = "SAVE_SYSTEM_API_COIN";

export const SAVE_BETSHARE_TODAY_BETWIN = "SAVE_BETSHARE_TODAY_BETWIN";
export const SAVE_BETSHARE_BETTING = "SAVE_BETSHARE_BETTING";

export const SET_SYS_EXCHANGE_INFO = "SET_SYS_EXCHANGE_INFO";

export const SAVE_APP_LANGUAGE_CONFIG = "SAVE_APP_LANGUAGE_CONFIG";
export const SAVE_APP_LANGUAGE = "SAVE_APP_LANGUAGE";
export const SET_APP_LONGQUEUE = "SET_APP_LONGQUEUE";

export const SAVE_CMS_DISCOUNTS = "SAVE_CMS_DISCOUNTS";

export const SAVE_AGENT_DESC = "SAVE_AGENT_DESC";

export const SET_COLLECT_GAMES = "SET_COLLECT_GAMES";
export const DEL_COLLECT_GAME = "DEL_COLLECT_GAME";
export const ADD_COLLECT_GAME = "ADD_COLLECT_GAME";
export const SET_CHAT_TEAM = "SET_CHAT_TEAM";
export const SAVE_SYSTEM_REALNAME = "SAVE_SYSTEM_REALNAME";
